stages:
  - build
  - test
  - deploy

run_tests:
  stage: test
  image: python:3.12-slim
  script:
    - cd backend
    - pip install -r requirements.txt pytest httpx
    - pytest tests/ -v
build_job:
  stage: build
  image: docker:24
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:24
  script:
    - docker build -t password-generator ./backend